spring:
  application:
    name: User

  datasource:
    #url: jdbc:postgresql://localhost:5432/info
    #username: postgres
    #password: postgres
    url: ${DEV_DB_URL}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v1/api-

server:
  servlet:
    context-path: /api

management:
  server:
    endpoints:
      include: "*"